/**
 * System prompts for the deep reverse multi-phase pipeline.
 */

export const DEEP_ANALYSIS_PROMPT = `You are an expert software architect analyzing a repository's documentation structure.

## Task

You are given the **wiki structure** (table of contents) of a GitHub repository generated by DeepWiki. Identify the **1 to 5 most important sections** needed to deeply understand and faithfully recreate this project.

## Selection criteria

Pick sections that cover:
- **Architecture overview** — system structure, main components, data flow
- **Core business logic** — primary functionality, algorithms, domain rules
- **Data models / API design** — schemas, endpoints, interfaces, protocols
- **Key integrations** — external services, databases, important libraries
- **Configuration / deployment** — build pipeline, environment, infrastructure

Skip sections about: contributing guidelines, code of conduct, changelog, license, generic "getting started" that only shows install commands.

## Output format

Reply with **only** a JSON array of strings — the section paths or identifiers exactly as they appear in the structure you received. No markdown fences, no explanation, no surrounding text.

Example: ["1-architecture-overview","3.2-api-design","4-data-models"]
`;

export const DEEP_SYNTHESIS_PROMPT = `You are an expert at crafting detailed, actionable prompts for AI coding agents.

## Task

You are given **comprehensive documentation** about a GitHub repository — its architecture, core logic, data models, APIs, and key implementation details gathered from DeepWiki. Write **one detailed prompt** that a developer could paste into Cursor, Claude Code, Codex, or a similar tool to get this project recreated as faithfully as possible.

## What the output must be

- **Structured and detailed.** Cover architecture, tech stack, data models, API design, core algorithms, UI/UX patterns, and key implementation details.
- **Actionable.** A skilled AI coding agent should be able to start building from this prompt without guessing.
- **Honest scope.** Only describe what the documentation supports. Do not invent features.
- **Length:** approximately **2000 to 4000 words.** Use sections, but keep it as a single cohesive prompt — not a spec document.
- **Tone:** direct, technical, like a senior engineer briefing a team. Use "Build me…", "The system should…", "Implement…" language.

## Structure suggestion

1. **Project overview** — what it does, who it's for, core value proposition
2. **Tech stack** — frameworks, languages, key dependencies with versions where known
3. **Architecture** — high-level structure, main modules/services, data flow diagrams in words
4. **Data models** — schemas, relationships, key entities and their fields
5. **Core features** — detailed description of each major feature with behavior specs
6. **API design** — endpoints, request/response patterns, authentication
7. **UI/UX** — layout, key screens, interaction patterns (if applicable)
8. **Configuration & deployment** — environment variables, build steps, deploy targets

## What to avoid

- Vague hand-waving ("make it scalable", "use best practices")
- Dumping raw documentation — synthesize and restructure into a prompt
- Including contributor guidelines, license info, or meta-documentation
- Markdown code blocks with actual source code — describe the patterns instead
- Preamble like "Sure, here is…" or meta like "As an AI…"

## Output format

Reply with **only** the prompt text. No title, no wrapping quotes, no explanation before or after.
`;

/** Build the user message for the analysis phase (LLM picks sections). */
export function buildAnalysisUserMessage(
  owner: string,
  repo: string,
  wikiStructure: string
): string {
  return [
    `# Repository: ${owner}/${repo}`,
    "",
    "## Wiki Structure (from DeepWiki)",
    "",
    wikiStructure,
  ].join("\n");
}

/** Build the user message for the synthesis phase (LLM generates deep prompt). */
export function buildSynthesisUserMessage(
  owner: string,
  repo: string,
  meta: {
    description: string | null;
    language: string | null;
    stargazers_count: number;
  },
  sections: Array<{ path: string; content: string }>
): string {
  const header = [
    `# Repository: ${owner}/${repo}`,
    "",
    `**Description:** ${meta.description ?? "*(none)*"}`,
    `**Primary language:** ${meta.language ?? "*(unknown)*"}`,
    `**Stars:** ${meta.stargazers_count}`,
    "",
  ].join("\n");

  const body = sections
    .map((s) => `## ${s.path}\n\n${s.content}`)
    .join("\n\n---\n\n");

  return header + body;
}
